apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: rayltics/auth-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3333
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_PORT
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AUTH_MONGO_URI
            - name: NO_COLOR
              value: "true"